#!/usr/bin/env node

/**
 * Scans `assets/exams/<section>/<subject>/` and writes `src/data/exams.generated.ts`.
 *
 * Metro can only bundle images referenced by static `require()` calls, so this
 * script turns the folder contents into that list.
 *
 * File naming: `<examKey>_page-<pageNumber>.<ext>`, e.g. `2026_page-01.webp`.
 * Pages sharing the same `<examKey>` form one exam. Images that don't follow the
 * pattern are grouped into a single exam per folder.
 *
 * Usage: npm run generate:exams
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const examsDir = path.join(root, 'assets', 'exams');
const outputFile = path.join(root, 'src', 'data', 'exams.generated.ts');
const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp']);
const PAGE_PATTERN = /^(.+?)_page-(\d+)$/i;

const naturalCompare = (a, b) => a.localeCompare(b, undefined, { numeric: true });
const subdirectories = (dir) =>
  fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort(naturalCompare);

const lines = [
  '// This file is generated by scripts/generate-exams.js — do not edit by hand.',
  '// Run `npm run generate:exams` after adding or removing images in assets/exams/.',
  '',
  'export type ExamPages = { key: string; pages: number[] };',
  '',
  '/** Keyed by `<section>/<subject>` folder names. */',
  'export const examsByFolder: Record<string, ExamPages[]> = {',
];

for (const section of subdirectories(examsDir)) {
  for (const subject of subdirectories(path.join(examsDir, section))) {
    const folder = `${section}/${subject}`;
    const groups = new Map();

    for (const file of fs.readdirSync(path.join(examsDir, folder))) {
      if (!IMAGE_EXTENSIONS.has(path.extname(file).toLowerCase())) continue;
      const match = path.basename(file, path.extname(file)).match(PAGE_PATTERN);
      const key = match ? match[1] : 'default';
      const order = match ? match[2] : file;
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key).push({ file, order });
    }

    lines.push(`  '${folder}': [`);
    for (const key of [...groups.keys()].sort(naturalCompare)) {
      const pages = groups.get(key).sort((a, b) => naturalCompare(a.order, b.order));
      lines.push(`    {`, `      key: '${key}',`, `      pages: [`);
      for (const { file } of pages) {
        lines.push(`        require('@/assets/exams/${folder}/${file}'),`);
      }
      lines.push(`      ],`, `    },`);
    }
    lines.push(`  ],`);

    const pageCount = [...groups.values()].reduce((sum, pages) => sum + pages.length, 0);
    console.log(`✓ ${folder}: ${groups.size} exam(s), ${pageCount} page(s)`);
  }
}

lines.push('};', '');
fs.writeFileSync(outputFile, lines.join('\n'));
console.log(`Wrote ${path.relative(root, outputFile)}`);
