#!/usr/bin/env node

/**
 * Scans each subject folder in `assets/` and writes `src/data/exams.generated.ts`.
 *
 * Metro can only bundle images referenced by static `require()` calls, so this
 * script turns the folder contents into that list.
 *
 * File naming: `<examKey>_page-<pageNumber>.<ext>`, e.g. `6_page-0001.jpg`.
 * Pages sharing the same `<examKey>` form one exam. Images that don't follow the
 * pattern are grouped into a single exam per folder.
 *
 * Usage: npm run generate:exams
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const subjectsFile = path.join(root, 'src', 'data', 'subjects.ts');
const outputFile = path.join(root, 'src', 'data', 'exams.generated.ts');
const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp']);
const PAGE_PATTERN = /^(.+?)_page-(\d+)$/i;

// Read the `folder: '...'` values from subjects.ts so subject folders are defined in one place.
const folders = [...fs.readFileSync(subjectsFile, 'utf8').matchAll(/folder:\s*'([^']+)'/g)].map(
  (match) => match[1]
);

const naturalCompare = (a, b) => a.localeCompare(b, undefined, { numeric: true });

const lines = [
  '// This file is generated by scripts/generate-exams.js — do not edit by hand.',
  '// Run `npm run generate:exams` after adding or removing images in assets/.',
  '',
  'export type ExamPages = { key: string; pages: number[] };',
  '',
  'export const examsByFolder: Record<string, ExamPages[]> = {',
];

for (const folder of folders) {
  const dir = path.join(root, 'assets', folder);
  if (!fs.existsSync(dir)) {
    console.warn(`⚠ assets/${folder} not found — skipping`);
    lines.push(`  '${folder}': [],`);
    continue;
  }

  const groups = new Map();
  for (const file of fs.readdirSync(dir)) {
    const ext = path.extname(file).toLowerCase();
    if (!IMAGE_EXTENSIONS.has(ext)) continue;
    const match = path.basename(file, path.extname(file)).match(PAGE_PATTERN);
    const key = match ? match[1] : 'default';
    const order = match ? Number(match[2]) : file;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push({ file, order });
  }

  lines.push(`  '${folder}': [`);
  for (const key of [...groups.keys()].sort(naturalCompare)) {
    const pages = groups
      .get(key)
      .sort((a, b) => naturalCompare(String(a.order), String(b.order)));
    lines.push(`    {`, `      key: '${key}',`, `      pages: [`);
    for (const { file } of pages) {
      lines.push(`        require('@/assets/${folder}/${file}'),`);
    }
    lines.push(`      ],`, `    },`);
  }
  lines.push(`  ],`);

  const pageCount = [...groups.values()].reduce((sum, pages) => sum + pages.length, 0);
  console.log(`✓ assets/${folder}: ${groups.size} exam(s), ${pageCount} page(s)`);
}

lines.push('};', '');
fs.writeFileSync(outputFile, lines.join('\n'));
console.log(`Wrote ${path.relative(root, outputFile)}`);
