// This file is generated by scripts/generate-exams.js — do not edit by hand.
// Run `npm run generate:exams` after adding or removing images in assets/.

export type ExamPages = { key: string; pages: number[] };

export const examsByFolder: Record<string, ExamPages[]> = {
  'fiqah': [
    {
      key: '6',
      pages: [
        require('@/assets/fiqah/6_page-0001.jpg'),
        require('@/assets/fiqah/6_page-0002.jpg'),
        require('@/assets/fiqah/6_page-0003.jpg'),
        require('@/assets/fiqah/6_page-0004.jpg'),
        require('@/assets/fiqah/6_page-0005.jpg'),
        require('@/assets/fiqah/6_page-0006.jpg'),
        require('@/assets/fiqah/6_page-0007.jpg'),
        require('@/assets/fiqah/6_page-0008.jpg'),
        require('@/assets/fiqah/6_page-0009.jpg'),
        require('@/assets/fiqah/6_page-0010.jpg'),
        require('@/assets/fiqah/6_page-0011.jpg'),
        require('@/assets/fiqah/6_page-0012.jpg'),
      ],
    },
  ],
};
